[server]
hostname = "wso2am-9443-snipkode.cloud.okteto.net"
base_path = "https://$ref{server.hostname}"
server_role = "default"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.apim_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2AM_DB;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

# [database.apim_db]
# type = "mysql"
# url = "jdbc:mysql://mysql:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
# username = "wso2carbon"
# password = "wso2carbon"
# driver = "com.mysql.cj.jdbc.Driver"

# [database.shared_db]
# type = "mysql"
# url = "jdbc:mysql://mysql:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
# username = "wso2carbon"
# password = "wso2carbon"
# driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

#[keystore.primary]
#file_name =  "wso2carbon.jks"
#type =  "JKS"
#password =  "wso2carbon"
#alias =  "wso2carbon"
#key_password =  "wso2carbon"

#[keystore.internal]
#file_name =  "wso2carbon.jks"
#type =  "JKS"
#password =  "wso2carbon"
#alias =  "wso2carbon"
#key_password =  "wso2carbon"

[[apim.gateway.environment]]
name = "Default"
type = "hybrid"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url = true
service_url = "https://gateways-stage-snipkode.cloud.okteto.net/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint = "ws://ws2-stage-snipkode.cloud.okteto.net"
wss_endpoint = "wss://ws-stage-snipkode.cloud.okteto.net"
http_endpoint = "http://gateways2-stage-snipkode.cloud.okteto.net"
https_endpoint = "https://gateways-stage-snipkode.cloud.okteto.net"
websub_event_receiver_http_endpoint = "http://websub2-stage-snipkode.cloud.okteto.net"
websub_event_receiver_https_endpoint = "https://websub-stage-snipkode.cloud.okteto.net"

[[apim.gateway.environment]]
name = "Production"
type = "production"
display_in_api_console = true
description = "This is the gateway that handles production token traffic."
show_as_token_endpoint_url = true
service_url = "https://localhost:9445/services/"
username= "admin"
password= "admin"
ws_endpoint = "ws://localhost:9099"
wss_endpoint = "wss://localhost:8099"
http_endpoint = "http://localhost:8282"
https_endpoint = "https://localhost:8245"

[[apim.gateway.environment]]
name = "Sandbox"
type = "sandbox"
display_in_api_console = true
description = "This is the gateway that handles sandbox token traffic."
show_as_token_endpoint_url = false
service_url = "https://localhost:9448/services/"
username= "admin"
password= "admin"
ws_endpoint = "ws://localhost:9199"
wss_endpoint = "wss://localhost:8199"
http_endpoint = "http://localhost:8285"
https_endpoint = "https://localhost:8248"

[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default", "Sandbox", "Production"]

[apim.analytics]
enable = true
config_endpoint = "https://analitycs-stage-snipkode.cloud.okteto.net/auth/v1"
auth_token = ""

[apim.devportal]
url = "https://wso2am-9443-snipkode.cloud.okteto.net/devportal"

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","apikey","Internal-Key"]
allow_credentials = false

[[event_handler]]
name="userPostSelfRegistration"
subscriptions=["POST_ADD_USER"]

[service_provider]
sp_name_regex = "^[\\sa-zA-Z0-9._-]*$"

[database.local]
url = "jdbc:h2:./repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"

[transport.http.properties]
proxyPort = 80

[transport.https.properties]
proxyPort = 443 

#ENABLE ADMIN SERVICES WSDL
[admin_service.wsdl]
enable = true

[apim.sdk]
supported_languages = ["android", "java", "scala", "csharp", "dart", "flash", "groovy", "javascript", "php", "typescript-node", "ruby", "swift", "flash", "python", "perl"]
